//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part7_StoredProcedure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pragim_Employee_1
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int Salary { get; set; }
        public int DeptID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> CodeFirst_Department_Id { get; set; }
    
        public virtual tbl_Pragim_Department1 tbl_Pragim_Department1 { get; set; }
    }
}
