//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTestEntities : DbContext
    {
        public dbTestEntities()
            : base("name=dbTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Pragim_Entity_Department> tbl_Pragim_Entity_Department { get; set; }
        public virtual DbSet<tbl_Pragim_Entity_Employee> tbl_Pragim_Entity_Employee { get; set; }
    }
}
